target("Windowing")
    set_kind("shared")
    add_rules("chozo_module", "export_header")
    add_deps("Core", "RenderCore")
    add_packages("glfw", {public = true})
    add_files("Private/GenericPlatform/GLFW/GLFWInputImpl.cpp") 