-- Define a rule for auto-generating export headers
rule("export_header")
    on_config(function (target)
        local kind = target:kind()

        if kind == "binary" then 
            return 
        end

        -- Helper: CamelCase to SNAKE_CASE
        local function get_api_prefix(name)
            -- Insert underscore between lowercase and uppercase letters
            local prefix = name:gsub("([a-z])([A-Z])", "%1_%2"):upper()
            return prefix
        end

        local prefix = get_api_prefix(target:name())
        local header_name = target:name() .. "Export.h"
        local gen_dir = path.join(vformat("$(builddir)"), ".gens", target:name(), "include")
        local header_path = path.join(gen_dir, header_name)

        local lines = {
            "#pragma once",
            "// This file is auto-generated by xmake. DO NOT EDIT.",
            ""
        }

        -- [Note] Logic Branch: Shared vs Static
        if kind == "shared" then
            target:add("defines", prefix .. "_EXPORTS")
            table.insert(lines, "#ifdef " .. prefix .. "_EXPORTS")
            table.insert(lines, "    #define " .. prefix .. "_API CHOZO_DLL_EXPORT")
            table.insert(lines, "#else")
            table.insert(lines, "    #define " .. prefix .. "_API CHOZO_DLL_IMPORT")
            table.insert(lines, "#endif")
        else
            -- [Note] For static libs, API macro is empty
            table.insert(lines, "#define " .. prefix .. "_API")
        end

        -- Only write if content changed (to avoid unnecessary recompilation)
        local content = table.concat(lines, "\n")
        if not os.isdir(gen_dir) then os.mkdir(gen_dir, true) end
        
        local old_content = os.isfile(header_path) and io.readfile(header_path) or nil
        if content ~= old_content then
            io.writefile(header_path, content)
        end

        target:add("includedirs", gen_dir, {public = true})
        target:add("forceincludes", header_name)
    end)