

-- Define a rule for auto-generating export headers
rule("export_header")
    on_config(function (target)
        import("core.project.project")

        -- Helper: CamelCase to SNAKE_CASE
        local function get_api_prefix(name)
            -- Insert underscore between lowercase and uppercase letters
            local prefix = name:gsub("([a-z])([A-Z])", "%1_%2"):upper()
            return prefix
        end
        
        local build_dir = vformat("$(builddir)")
        local gen_dir = path.join(build_dir, ".gens", "ChozoBase", "include")
        local header_path = path.join(gen_dir, "ChozoExport.h")

        local lines = {
            "// This file is auto-generated by xmake. DO NOT EDIT.",
            "#ifndef CHOZO_EXPORT_H",
            "#define CHOZO_EXPORT_H",
            "",
            "/* --- Base Platform Macros --- */",
            "#if defined(_WIN32)",
            "    #define CHOZO_DLL_EXPORT __declspec(dllexport)",
            "    #define CHOZO_DLL_IMPORT __declspec(dllimport)",
            "#else",
            "    #if defined(__GNUC__) || defined(__clang__)",
            "        #define CHOZO_DLL_EXPORT __attribute__((visibility(\"default\")))",
            "        #define CHOZO_DLL_IMPORT __attribute__((visibility(\"default\")))",
            "    #else",
            "        #define CHOZO_DLL_EXPORT",
            "        #define CHOZO_DLL_IMPORT",
            "    #endif",
            "#endif",
            ""
        }

        -- Iterate through ALL targets in the project to generate their API macros
        -- project.targets() returns a table of all defined targets
        for _, t in pairs(project.targets()) do
            if t:get("kind") == "shared" then
                local prefix = get_api_prefix(t:name())
                table.insert(lines, "/* --- " .. t:name() .. " --- */")
                table.insert(lines, "#ifdef " .. prefix .. "_EXPORTS")
                table.insert(lines, "    #define " .. prefix .. "_API CHOZO_DLL_EXPORT")
                table.insert(lines, "#else")
                table.insert(lines, "    #define " .. prefix .. "_API CHOZO_DLL_IMPORT")
                table.insert(lines, "#endif\n")
            end
        end

        table.insert(lines, "#endif // CHOZO_EXPORT_H")

        -- Only write if content changed (to avoid unnecessary recompilation)
        local content = table.concat(lines, "\n")
        
        if not os.isdir(gen_dir) then 
            os.mkdir(gen_dir, true)
        end

        local old_content = nil
        if os.isfile(header_path) then
            old_content = io.readfile(header_path)
        end

        if content ~= old_content then
            io.writefile(header_path, content)
        end

        -- Add the auto-generated directory to include path
        target:add("includedirs", gen_dir, {public = true})
        target:add("forceincludes", "ChozoExport.h", {public = true})
    end)