if(MSVC)
    set(MODULE_COMPILE_OPTIONS /W4 /wd4201)
    set(MODULE_LINK_OPTIONS "/ignore:4099")
else()
    set(MODULE_COMPILE_OPTIONS -Wall -Wextra)
endif()

function(add_chozo_core_module)
    cmake_parse_arguments(MODULE "" "NAME" "INCLUDE;SOURCE" ${ARGN})
    message(STATUS "CHOZO CORE MODULE          ${MODULE_NAME}")
    set(CZ_CORE_MODULE_LIST "${CZ_CORE_MODULE_LIST};${MODULE_NAME}" CACHE STRING "" FORCE)
    add_library(${MODULE_NAME} STATIC ${MODULE_INCLUDE} ${MODULE_SOURCE})
    target_include_directories(${MODULE_NAME} PRIVATE ${CHOZO_INCLUDE_DIR})
    target_compile_options(${MODULE_NAME} PRIVATE ${MODULE_COMPILE_OPTIONS})
    target_link_options(${MODULE_NAME} PRIVATE ${MODULE_LINK_OPTIONS})
    set_target_properties(${MODULE_NAME} PROPERTIES FOLDER ${CZ_CORE_MODULE_FOLDER})
endfunction()